// <auto-generated />
using System;
using Fiap.Banco.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Banco.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Banco.API.Models.Agencia", b =>
                {
                    b.Property<int>("idAgencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAgencia"));

                    b.Property<string>("dsEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("nmAgencia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("idAgencia");

                    b.ToTable("Agencias");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Banco", b =>
                {
                    b.Property<int>("idBanco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idBanco"));

                    b.Property<DateTime>("dtCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("nomeBanco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("idBanco");

                    b.ToTable("Bancos");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.Property<int>("agenciaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("id");

                    b.HasIndex("agenciaId");

                    b.ToTable("AgenciaClientes", (string)null);

                    b.HasDiscriminator<string>("TipoCliente").HasValue("Cliente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Contratacao", b =>
                {
                    b.Property<int>("idContratacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idContratacao"));

                    b.Property<int>("clienteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("dataSolicitacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("observacao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<int>("produtoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.HasKey("idContratacao");

                    b.HasIndex("clienteId");

                    b.HasIndex("produtoId");

                    b.ToTable("Contratacoes");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Funcionario", b =>
                {
                    b.Property<int>("idFuncionarios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idFuncionarios"));

                    b.HasKey("idFuncionarios");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Produto", b =>
                {
                    b.Property<int>("idProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idProduto"));

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("NVARCHAR2(21)");

                    b.Property<int>("ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("nomeProduto")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("idProduto");

                    b.ToTable("Produtos");

                    b.HasDiscriminator<string>("TipoProduto").HasValue("Produto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.PessoaFisica", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Cliente");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.Property<DateTime>("dataNascimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasDiscriminator().HasValue("PF");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.PessoaJuridica", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Cliente");

                    b.Property<string>("cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)");

                    b.Property<string>("razaoSocial")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasDiscriminator().HasValue("PJ");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Emprestimo", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Produto");

                    b.Property<int>("quantidadeParcelas")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("taxaJurosMensal")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<decimal>("valorSolicitado")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasDiscriminator().HasValue("Emprestimo");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.MaquinaDeCartao", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Produto");

                    b.Property<decimal>("aluguelMensal")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("taxaMdrPercentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)");

                    b.HasDiscriminator().HasValue("MaquinaDeCartao");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.ReceberSalario", b =>
                {
                    b.HasBaseType("Fiap.Banco.API.Models.Produto");

                    b.Property<string>("cnpjConvenio")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)");

                    b.Property<decimal>("limiteAntecipacaoPercentual")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)");

                    b.HasDiscriminator().HasValue("ReceberSalario");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Cliente", b =>
                {
                    b.HasOne("Fiap.Banco.API.Models.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("agenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("Fiap.Banco.API.Models.Contratacao", b =>
                {
                    b.HasOne("Fiap.Banco.API.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("clienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fiap.Banco.API.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("produtoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
